apiVersion: v1
kind: Service
metadata:
  name: biomni-svc
  namespace: biomni
  labels:
    app: biomni-api
spec:
  selector:
    app: biomni-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: gradio
      port: 7860
      targetPort: 7860
  type: ClusterIP
