"""Population pharmacokinetics and pharmacodynamics (PopPK/PD) tools.

Covers NONMEM control stream generation and output parsing, nlmixr2
population fitting, mrgsolve simulation, model diagnostics (GOF, VPC,
NPDE), covariate analysis, clinical trial simulation, and model
selection guidance.
"""

import os
import re

import numpy as np

from biomni.utils import run_r_code


# ─────────────────────────────────────────────────────────────────────────────
# NONMEM Control Stream Generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_nonmem_control_stream(
    model_type: str,
    dataset_path: str,
    output_path: str = "./run001.ctl",
    pk_parameters: dict = None,
    error_model: str = "proportional",
    covariates: list = None,
    omega_structure: str = "diagonal",
    estimation_method: str = "FOCE-I",
    n_subjects_approx: int = 100,
) -> str:
    """Generate a NONMEM control stream (.ctl) file for population PK/PD analysis.

    Supports 1-, 2-, and 3-compartment PK models (IV and oral), Emax PD,
    and indirect response models. The generated file is ready to run with
    NONMEM 7.4+.

    Parameters
    ----------
    model_type : str
        Model structure: '1cmt_iv', '1cmt_oral', '2cmt_iv', '2cmt_oral',
        '3cmt_iv', '3cmt_oral', 'emax', 'indirect_response'.
    dataset_path : str
        Path to the NONMEM-formatted dataset (.csv with ID, TIME, DV, AMT, etc.).
    output_path : str
        Where to write the .ctl file.
    pk_parameters : dict
        Initial estimates for PK parameters. Keys depend on model_type.
        Example for 2cmt_oral: {'CL': 5, 'V1': 50, 'Q': 2, 'V2': 100, 'KA': 1.0}
    error_model : str
        Residual error: 'additive', 'proportional', 'combined'.
    covariates : list
        Covariate effects to include. E.g. ['WT on CL', 'WT on V1', 'AGE on CL'].
    omega_structure : str
        IIV structure: 'diagonal' or 'block'.
    estimation_method : str
        NONMEM estimation: 'FO', 'FOCE', 'FOCE-I', 'SAEM', 'BAYES'.
    n_subjects_approx : int
        Approximate N for $SIZES recommendation.
    """
    log = ["=" * 60]
    log.append("NONMEM CONTROL STREAM GENERATOR")
    log.append("=" * 60)
    log.append(f"Model type         : {model_type}")
    log.append(f"Dataset            : {dataset_path}")
    log.append(f"Error model        : {error_model}")
    log.append(f"Estimation method  : {estimation_method}")

    defaults = {
        "1cmt_iv":    {"CL": 5.0,  "V": 50.0},
        "1cmt_oral":  {"CL": 5.0,  "V": 50.0,  "KA": 1.0},
        "2cmt_iv":    {"CL": 5.0,  "V1": 30.0, "Q": 2.0,  "V2": 80.0},
        "2cmt_oral":  {"CL": 5.0,  "V1": 30.0, "Q": 2.0,  "V2": 80.0, "KA": 1.0},
        "3cmt_iv":    {"CL": 5.0,  "V1": 10.0, "Q2": 2.0, "V2": 60.0, "Q3": 1.0, "V3": 200.0},
        "3cmt_oral":  {"CL": 5.0,  "V1": 10.0, "Q2": 2.0, "V2": 60.0, "Q3": 1.0, "V3": 200.0, "KA": 1.0},
        "emax":       {"EMAX": 100.0, "EC50": 1.0, "E0": 5.0},
        "indirect_response": {"EMAX": 2.0, "EC50": 1.0, "KIN": 10.0, "KOUT": 0.1},
    }
    params = pk_parameters or defaults.get(model_type, {"CL": 5.0, "V": 50.0})

    # Build NONMEM blocks
    ctl_lines = []

    ctl_lines.append(f"; NONMEM Control Stream — {model_type.upper()}")
    ctl_lines.append("; Generated by Biomni PKPD Tools")
    ctl_lines.append(f"; Dataset: {dataset_path}")
    ctl_lines.append("")
    ctl_lines.append(f"$PROBLEM {model_type.upper()} Population PK Analysis")
    ctl_lines.append("")
    ctl_lines.append("$INPUT ID TIME DV AMT EVID MDV CMT RATE" +
                     (" WT AGE SEX" if covariates else ""))
    ctl_lines.append(f"$DATA {dataset_path} IGNORE=@")
    ctl_lines.append("")
    ctl_lines.append(f"$SIZES LIM6={max(200, n_subjects_approx * 3)}")
    ctl_lines.append("")

    # SUBROUTINE selection
    subroutine_map = {
        "1cmt_iv": "ADVAN1 TRANS2",
        "1cmt_oral": "ADVAN2 TRANS2",
        "2cmt_iv": "ADVAN3 TRANS4",
        "2cmt_oral": "ADVAN4 TRANS4",
        "3cmt_iv": "ADVAN11 TRANS4",
        "3cmt_oral": "ADVAN12 TRANS4",
    }

    if model_type in subroutine_map:
        ctl_lines.append(f"$SUBROUTINE {subroutine_map[model_type]}")
        ctl_lines.append("")
        ctl_lines.append("$PK")
        ctl_lines.append("  ; Individual PK parameters with IIV")
        for i, (name, val) in enumerate(params.items(), 1):
            ctl_lines.append(f"  TV{name}  = THETA({i})")
            ctl_lines.append(f"  {name}    = TV{name} * EXP(ETA({i}))")
        if covariates:
            ctl_lines.append("")
            ctl_lines.append("  ; Covariate effects")
            for cov in covariates:
                parts = cov.split(" on ")
                if len(parts) == 2:
                    cov_var, pk_par = parts[0].strip(), parts[1].strip()
                    ctl_lines.append(f"  ; {cov_var} effect on {pk_par}")
                    if "WT" in cov_var:
                        ctl_lines.append(
                            f"  {pk_par} = TV{pk_par} * (WT/70)**THETA({len(params)+covariates.index(cov)+1}) * EXP(ETA({covariates.index(cov)+1}))"
                        )
        ctl_lines.append("")
    else:
        # ODE-based models (Emax, indirect response)
        ctl_lines.append("$SUBROUTINE ADVAN13 TOL=6")
        ctl_lines.append("")
        ctl_lines.append("$MODEL NCOMPARTMENTS=2")
        ctl_lines.append("")
        ctl_lines.append("$PK")
        for i, (name, val) in enumerate(params.items(), 1):
            ctl_lines.append(f"  {name} = THETA({i}) * EXP(ETA({i}))")
        ctl_lines.append("")
        ctl_lines.append("$DES")
        if model_type == "emax":
            ctl_lines.append("  CONC = A(1) / V")
            ctl_lines.append("  EFFECT = E0 + EMAX * CONC / (EC50 + CONC)")
            ctl_lines.append("  DADT(1) = -CL * CONC")
        elif model_type == "indirect_response":
            ctl_lines.append("  CONC   = A(1) / V")
            ctl_lines.append("  INHIB  = EMAX * CONC / (EC50 + CONC)")
            ctl_lines.append("  DADT(1) = -CL * CONC")
            ctl_lines.append("  DADT(2) = KIN * (1 - INHIB) - KOUT * A(2)")
        ctl_lines.append("")

    # ERROR block
    ctl_lines.append("$ERROR")
    ctl_lines.append("  IPRED = F")
    if error_model == "proportional":
        ctl_lines.append("  W     = IPRED * THETA(999)")
        ctl_lines.append("  Y     = IPRED + W * EPS(1)")
        ctl_lines.append("  IWRES = (DV - IPRED) / W")
    elif error_model == "additive":
        ctl_lines.append("  W     = THETA(999)")
        ctl_lines.append("  Y     = IPRED + W * EPS(1)")
        ctl_lines.append("  IWRES = (DV - IPRED) / W")
    else:  # combined
        ctl_lines.append("  W     = SQRT((THETA(999)*IPRED)**2 + THETA(1000)**2)")
        ctl_lines.append("  Y     = IPRED + W * EPS(1)")
        ctl_lines.append("  IWRES = (DV - IPRED) / W")
    ctl_lines.append("")

    # THETA initial estimates
    ctl_lines.append("$THETA")
    for name, val in params.items():
        ctl_lines.append(f"  (0, {val:.3g})      ; TV{name}")
    ctl_lines.append("  (0, 0.1)           ; Proportional error (sigma/RV)")
    ctl_lines.append("")

    # OMEGA block
    ctl_lines.append("$OMEGA")
    if omega_structure == "block" and len(params) >= 2:
        n = len(params)
        ctl_lines.append(f"$OMEGA BLOCK({n})")
        for i in range(n):
            row = "  " + "  ".join(
                ["0.04" if j == i else "0.01" for j in range(i + 1)]
            )
            ctl_lines.append(row + f"  ; ETA({i+1})")
    else:
        for i, name in enumerate(params.keys(), 1):
            ctl_lines.append(f"  0.04              ; IIV-{name} (~20% CV)")
    ctl_lines.append("")
    ctl_lines.append("$SIGMA")
    ctl_lines.append("  1 FIXED           ; Proportional error placeholder")
    ctl_lines.append("")

    # Estimation
    method_map = {
        "FO": "0", "FOCE": "1", "FOCE-I": "1 INTERACTION",
        "SAEM": "SAEM", "BAYES": "BAYES NBURN=1000 NITER=3000",
    }
    est_str = method_map.get(estimation_method, "1 INTERACTION")
    ctl_lines.append(f"$ESTIMATION METHOD={est_str} MAXEVAL=9999 PRINT=5 NOABORT")
    ctl_lines.append("  SIGDIGITS=3 POSTHOC")
    ctl_lines.append("")
    ctl_lines.append("$COVARIANCE PRINT=E UNCONDITIONAL")
    ctl_lines.append("")
    ctl_lines.append("$TABLE ID TIME DV AMT EVID MDV CMT")
    ctl_lines.append("  IPRED CWRES IWRES NOPRINT ONEHEADER")
    ctl_lines.append("  FILE=sdtab001")
    ctl_lines.append("")
    ctl_lines.append("$TABLE ID ETA(1)")
    for i, name in enumerate(params.keys(), 2):
        ctl_lines.append(f"  ETA({i})")
    ctl_lines.append("  NOPRINT ONEHEADER FILE=patab001")

    ctl_content = "\n".join(ctl_lines)
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(ctl_content)

    log.append(f"\nControl stream written to: {output_path}")
    log.append(f"Parameters ({len(params)} fixed effects + IIV): {', '.join(params.keys())}")
    log.append("\n── Next Steps ──")
    log.append("  1. Verify $INPUT column order matches your dataset header.")
    log.append("  2. Review initial THETA estimates — should be within 10× of truth.")
    log.append("  3. Run: execute run001.ctl (PsN) or nm run001.ctl")
    log.append("  4. Check covariance step — successful = stable model.")
    log.append("  5. Evaluate diagnostics: GOF plots, CWRES vs TIME/PRED, VPC.")

    return "\n".join(log)


# ─────────────────────────────────────────────────────────────────────────────
# NONMEM Output Parser
# ─────────────────────────────────────────────────────────────────────────────

def parse_nonmem_output(
    lst_file_path: str,
    ext_file_path: str = None,
    cov_file_path: str = None,
) -> str:
    """Parse NONMEM .lst output file to extract parameter estimates and diagnostics.

    Extracts: objective function value (OFV), THETA estimates and RSE%,
    OMEGA (IIV) estimates, SIGMA estimates, covariance step status,
    condition number, and run summary.

    Parameters
    ----------
    lst_file_path : str
        Path to NONMEM .lst output file.
    ext_file_path : str
        Path to NONMEM .ext file (extended output, more precise estimates).
    cov_file_path : str
        Path to NONMEM .cov file (covariance matrix output).
    """
    log = ["=" * 60]
    log.append("NONMEM OUTPUT PARSER")
    log.append("=" * 60)
    log.append(f"LST file: {lst_file_path}")

    if not os.path.exists(lst_file_path):
        return f"Error: LST file not found at {lst_file_path}"

    with open(lst_file_path, "r") as f:
        lst_content = f.read()

    # OFV
    ofv_match = re.search(r"#OBJV:\s*\*?\s*([-\d.]+)", lst_content)
    if ofv_match:
        ofv = float(ofv_match.group(1))
        log.append("\n── Objective Function ──")
        log.append(f"  OFV (NONMEM): {ofv:.3f}")
        log.append("  AIC ≈ OFV + 2p  (p = number of estimated parameters)")
        log.append("  BIC ≈ OFV + p × ln(N)  (N = number of observations)")

    # Minimisation status
    if "MINIMIZATION SUCCESSFUL" in lst_content:
        log.append("\n  ✓ Minimisation: SUCCESSFUL")
    elif "MINIMIZATION TERMINATED" in lst_content:
        log.append("\n  ⚠ Minimisation: TERMINATED (check MAXEVAL, rounding errors)")
    elif "ROUNDING ERRORS" in lst_content:
        log.append("\n  ⚠ Minimisation: ROUNDING ERRORS — parameter estimates unreliable")

    # Covariance step
    if "COVARIANCE STEP ABORTED" in lst_content:
        log.append("  ⚠ Covariance step: ABORTED — model may be over-parameterised")
        log.append("    Try fixing problematic parameters or simplifying model.")
    elif "STANDARD ERROR OF ESTIMATE" in lst_content:
        log.append("  ✓ Covariance step: SUCCESSFUL")

    # THETA extraction
    theta_section = re.search(
        r"THETA - VECTOR OF FIXED EFFECTS PARAMETERS.*?\n(.*?)(?=OMEGA|SIGMA|#)",
        lst_content, re.DOTALL
    )
    if theta_section:
        log.append("\n── THETA (Fixed Effects) ──")
        theta_vals = re.findall(r"[-+]?\d*\.?\d+(?:[Ee][+-]?\d+)?", theta_section.group(1))
        for i, v in enumerate(theta_vals[:20], 1):
            log.append(f"  THETA({i}): {v}")

    # SE/RSE extraction
    se_section = re.search(
        r"STANDARD ERROR OF ESTIMATE.*?\n(.*?)(?=COVARIANCE|#|\Z)",
        lst_content, re.DOTALL
    )
    if se_section and theta_section:
        theta_vals_f = [float(v) for v in re.findall(r"[-+]?\d*\.?\d+(?:[Ee][+-]?\d+)?", theta_section.group(1))[:20]]
        se_vals = re.findall(r"[-+]?\d*\.?\d+(?:[Ee][+-]?\d+)?", se_section.group(1))[:20]
        log.append("\n── RSE% (Relative Standard Error) ──")
        log.append("  RSE < 25% considered acceptable for fixed effects")
        log.append("  RSE < 50% considered acceptable for variance parameters")
        for i, (th, se) in enumerate(zip(theta_vals_f, se_vals), 1):
            try:
                rse = abs(float(se) / th * 100)
                flag = "  ⚠ HIGH" if rse > 50 else ("  ⚠" if rse > 25 else "  ✓")
                log.append(f"  THETA({i}): estimate={th:.4g}  SE={se}  RSE={rse:.1f}%{flag}")
            except Exception:
                pass

    # Condition number
    cn_match = re.search(r"CONDITION NUMBER OF FINAL R MATRIX:\s*([\d.E+\-]+)", lst_content)
    if cn_match:
        cn = float(cn_match.group(1))
        log.append("\n── Condition Number ──")
        log.append(f"  Condition number: {cn:.2e}")
        if cn > 1e7:
            log.append("  ⚠ Condition number > 10⁷ — near-singular matrix; model instability.")
        elif cn > 1e4:
            log.append("  Condition number 10⁴–10⁷ — marginal stability; review correlation.")
        else:
            log.append("  ✓ Condition number < 10⁴ — stable model.")

    log.append("\n── Interpretation Guide ──")
    log.append("  Acceptable model criteria:")
    log.append("  • Minimisation successful")
    log.append("  • Covariance step successful")
    log.append("  • RSE < 25% for THETAs, < 50% for OMEGAs/SIGMAs")
    log.append("  • Condition number < 10⁷")
    log.append("  • No ETA or EPS shrinkage > 30% (check GOF plots)")

    return "\n".join(log)


# ─────────────────────────────────────────────────────────────────────────────
# nlmixr2 Population PK Fitting
# ─────────────────────────────────────────────────────────────────────────────

def run_nlmixr2_model(
    dataset_path: str,
    model_type: str = "2cmt_oral",
    pk_parameters: dict = None,
    error_model: str = "prop",
    estimation_method: str = "saem",
    output_dir: str = "./nlmixr2_output",
    id_col: str = "ID",
    time_col: str = "TIME",
    dv_col: str = "DV",
    amt_col: str = "AMT",
    evid_col: str = "EVID",
) -> str:
    """Fit a population PK model using nlmixr2 in R.

    Reads the dataset, fits the specified model using SAEM (or FOCEI),
    generates goodness-of-fit plots, and saves parameter estimates.
    Supports 1cmt IV/oral, 2cmt IV/oral, and custom ODE models.

    Parameters
    ----------
    dataset_path : str
        Path to dataset CSV with columns: ID, TIME, DV, AMT, EVID (minimum).
    model_type : str
        '1cmt_iv', '1cmt_oral', '2cmt_iv', '2cmt_oral'.
    pk_parameters : dict
        Initial estimates for PK parameters (optional, uses defaults if None).
    error_model : str
        Residual error: 'prop' (proportional), 'add' (additive), 'prop+add'.
    estimation_method : str
        'saem' or 'focei'.
    output_dir : str
        Directory to save plots and parameter CSV.
    id_col, time_col, dv_col, amt_col, evid_col : str
        Column names in the dataset (in case of non-standard naming).
    """
    log = ["=" * 60]
    log.append("POPULATION PK FITTING — nlmixr2")
    log.append("=" * 60)
    log.append(f"Dataset     : {dataset_path}")
    log.append(f"Model       : {model_type}")
    log.append(f"Method      : {estimation_method.upper()}")

    os.makedirs(output_dir, exist_ok=True)

    model_funcs = {
        "1cmt_oral": """
  ini({
    lCL  ~ 1.5; lVc ~ 4.0; lKA ~ 0.0
    eta.CL ~ 0.04; eta.Vc ~ 0.04; eta.KA ~ 0.09
    prop.err <- 0.1
  })
  model({
    CL <- exp(lCL + eta.CL)
    Vc <- exp(lVc + eta.Vc)
    KA <- exp(lKA + eta.KA)
    linCmt() ~ prop(prop.err)
  })""",
        "2cmt_oral": """
  ini({
    lCL  ~ 1.5; lVc ~ 3.5; lQ ~ 0.7; lVp ~ 4.5; lKA ~ 0.0
    eta.CL ~ 0.04; eta.Vc ~ 0.04; eta.Q ~ 0.04; eta.Vp ~ 0.04; eta.KA ~ 0.09
    prop.err <- 0.1
  })
  model({
    CL <- exp(lCL + eta.CL)
    Vc <- exp(lVc + eta.Vc)
    Q  <- exp(lQ  + eta.Q)
    Vp <- exp(lVp + eta.Vp)
    KA <- exp(lKA + eta.KA)
    linCmt() ~ prop(prop.err)
  })""",
    }

    model_block = model_funcs.get(model_type, model_funcs["2cmt_oral"])

    r_code = f"""
suppressPackageStartupMessages({{
  library(nlmixr2)
  library(ggplot2)
  library(xpose.nlmixr2)
  library(vpc)
  library(dplyr)
}})

# Load data
pk_data <- read.csv("{dataset_path}")
names(pk_data)[names(pk_data) == "{id_col}"]   <- "ID"
names(pk_data)[names(pk_data) == "{time_col}"] <- "TIME"
names(pk_data)[names(pk_data) == "{dv_col}"]   <- "DV"
names(pk_data)[names(pk_data) == "{amt_col}"]  <- "AMT"
names(pk_data)[names(pk_data) == "{evid_col}"] <- "EVID"

cat("Data loaded:", nrow(pk_data), "rows,", length(unique(pk_data$ID)), "subjects\\n")

# Define model
pk_model <- function() {{
{model_block}
}}

# Fit model
cat("Fitting model with {estimation_method.upper()}...\\n")
fit <- nlmixr2(pk_model, pk_data, est = "{estimation_method}",
               control = {estimation_method}Control(print = 0))

# Print summary
cat("\\nPARAMETER_ESTIMATES_START\\n")
print(fit$parFixed)
cat("PARAMETER_ESTIMATES_END\\n")

cat("\\nVARIANCE_COMPONENTS_START\\n")
print(fit$omega)
cat("VARIANCE_COMPONENTS_END\\n")

cat("\\nOFV:", fit$objf, "\\n")

# Save estimates
write.csv(as.data.frame(fit$parFixed), "{output_dir}/param_estimates.csv")

# GOF plots
gof_data <- data.frame(
  PRED  = fit$PRED,
  IPRED = fit$IPRED,
  DV    = fit$DV,
  CWRES = fit$CWRES,
  TIME  = fit$TIME
)

p1 <- ggplot(gof_data, aes(x = PRED, y = DV)) +
  geom_point(alpha = 0.4, colour = "#2166AC") +
  geom_abline(slope = 1, intercept = 0, colour = "red", linetype = 2) +
  geom_smooth(method = "loess", se = TRUE, colour = "#4DAC26") +
  labs(title = "DV vs Population Prediction (PRED)",
       x = "PRED", y = "DV") + theme_bw(base_size = 12)

p2 <- ggplot(gof_data, aes(x = IPRED, y = DV)) +
  geom_point(alpha = 0.4, colour = "#D6604D") +
  geom_abline(slope = 1, intercept = 0, colour = "red", linetype = 2) +
  geom_smooth(method = "loess", se = TRUE, colour = "#4DAC26") +
  labs(title = "DV vs Individual Prediction (IPRED)",
       x = "IPRED", y = "DV") + theme_bw(base_size = 12)

p3 <- ggplot(gof_data, aes(x = TIME, y = CWRES)) +
  geom_point(alpha = 0.4, colour = "#762A83") +
  geom_hline(yintercept = c(-2, 0, 2), linetype = c(2, 1, 2),
             colour = c("red", "black", "red")) +
  geom_smooth(method = "loess", se = FALSE, colour = "#4DAC26") +
  labs(title = "CWRES vs TIME", x = "Time", y = "CWRES") +
  theme_bw(base_size = 12)

p4 <- ggplot(gof_data, aes(x = PRED, y = CWRES)) +
  geom_point(alpha = 0.4, colour = "#1A6648") +
  geom_hline(yintercept = c(-2, 0, 2), linetype = c(2, 1, 2),
             colour = c("red", "black", "red")) +
  geom_smooth(method = "loess", se = FALSE, colour = "#4DAC26") +
  labs(title = "CWRES vs PRED", x = "PRED", y = "CWRES") +
  theme_bw(base_size = 12)

library(patchwork)
gof_combined <- p1 + p2 + p3 + p4 + plot_layout(ncol = 2)
ggsave("{output_dir}/gof_plots.png", gof_combined, width = 12, height = 10, dpi = 150)

# VPC
cat("Generating VPC...\\n")
vpc_fit <- vpc_ui(fit, n = 500,
                  show = list(obs_dv = TRUE, pi = TRUE, ci = TRUE),
                  title = "Visual Predictive Check ({model_type})")
ggsave("{output_dir}/vpc.png", vpc_fit, width = 10, height = 6, dpi = 150)

cat("\\nFitting complete. Output saved to {output_dir}\\n")
"""

    r_output = run_r_code(r_code)

    if "Error" in r_output and "PARAMETER_ESTIMATES_START" not in r_output:
        log.append(f"\nR execution error:\n{r_output}")
        return "\n".join(log)

    log.append("\n── Parameter Estimates ──")
    in_block = False
    for line in r_output.splitlines():
        if "PARAMETER_ESTIMATES_START" in line:
            in_block = True
            continue
        if "PARAMETER_ESTIMATES_END" in line:
            in_block = False
            continue
        if in_block:
            log.append(f"  {line}")

    # Extract OFV
    ofv_match = re.search(r"OFV:\s*([-\d.]+)", r_output)
    if ofv_match:
        log.append(f"\n  OFV: {ofv_match.group(1)}")

    log.append(f"\nOutput files saved to {output_dir}/:")
    log.append("  param_estimates.csv  — fixed + random effects table")
    log.append("  gof_plots.png        — 4-panel GOF diagnostic plots")
    log.append("  vpc.png              — visual predictive check")

    log.append("\n── Diagnostic Interpretation ──")
    log.append("  GOF: DV vs PRED/IPRED should scatter around identity line with no trend.")
    log.append("  CWRES: should be N(0,1) distributed; |CWRES| > 4 are outliers.")
    log.append("  VPC: 80% of observations should fall within 10th–90th PI bands.")

    return "\n".join(log)


# ─────────────────────────────────────────────────────────────────────────────
# mrgsolve PK/PD Simulation
# ─────────────────────────────────────────────────────────────────────────────

def run_mrgsolve_simulation(
    model_type: str = "2cmt_oral",
    pk_parameters: dict = None,
    dosing_regimen: dict = None,
    n_subjects: int = 100,
    iiv_cv_percent: float = 30.0,
    simulation_duration_h: float = 168.0,
    output_dir: str = "./mrgsolve_output",
    compound_name: str = "compound",
    target_conc: float = None,
) -> str:
    """Simulate PK concentration-time profiles using mrgsolve in R.

    Performs stochastic population simulation incorporating inter-individual
    variability (IIV). Generates mean ± 90% prediction interval plots
    and calculates AUC, Cmax, Cmin at steady state.

    Parameters
    ----------
    model_type : str
        '1cmt_oral', '1cmt_iv', '2cmt_oral', '2cmt_iv'.
    pk_parameters : dict
        Population mean PK parameters (CL, Vc, etc.).
    dosing_regimen : dict
        Dosing scheme. Keys: 'dose_mg', 'interval_h', 'n_doses', 'route'.
        Example: {'dose_mg': 100, 'interval_h': 24, 'n_doses': 7, 'route': 'oral'}
    n_subjects : int
        Number of virtual subjects to simulate.
    iiv_cv_percent : float
        IIV as % CV (applied lognormally to all PK parameters).
    simulation_duration_h : float
        Total simulation time in hours.
    output_dir : str
        Directory to save plots and simulation output.
    compound_name : str
        Compound identifier for plot labels.
    target_conc : float
        Target therapeutic concentration (for % time above target calculation).
    """
    log = ["=" * 60]
    log.append("PK/PD SIMULATION — mrgsolve")
    log.append("=" * 60)
    log.append(f"Compound    : {compound_name}")
    log.append(f"Model       : {model_type}")
    log.append(f"N subjects  : {n_subjects}")
    log.append(f"IIV (%CV)   : {iiv_cv_percent}%")

    os.makedirs(output_dir, exist_ok=True)

    defaults_pk = {
        "1cmt_oral": {"CL": 5.0, "Vc": 50.0, "KA": 1.0},
        "1cmt_iv":   {"CL": 5.0, "Vc": 50.0},
        "2cmt_oral": {"CL": 5.0, "Vc": 30.0, "Q": 2.0, "Vp": 80.0, "KA": 1.0},
        "2cmt_iv":   {"CL": 5.0, "Vc": 30.0, "Q": 2.0, "Vp": 80.0},
    }
    params = pk_parameters or defaults_pk.get(model_type, {"CL": 5.0, "Vc": 50.0, "KA": 1.0})
    dosing = dosing_regimen or {"dose_mg": 100, "interval_h": 24, "n_doses": 7, "route": "oral"}

    params_r = ", ".join(f"{k} = {v}" for k, v in params.items())
    iiv_omega = (iiv_cv_percent / 100) ** 2
    _target_line = (
        "cat(sprintf('Time above target (%.1f): %.1f%%\\n', "
        + str(target_conc or 1.0)
        + ", 100 * mean(last_interval$Cp > "
        + str(target_conc or 1.0)
        + ")))"
        if target_conc
        else ""
    )

    r_code = f"""
suppressPackageStartupMessages({{
  library(mrgsolve)
  library(ggplot2)
  library(dplyr)
}})

set.seed(20240101)
N <- {n_subjects}

# Build model code
model_code <- '
$PARAM {params_r}
$CMT  {"DEPOT CENTRAL PERIPH" if "oral" in model_type else ("CENTRAL PERIPH" if "2cmt" in model_type else "CENTRAL")}
$GLOBAL double Cp = 0;
$ODE
{"dxdt_DEPOT   = -KA * DEPOT;" if "oral" in model_type else ""}
{"dxdt_CENTRAL = KA * DEPOT - (CL/Vc) * CENTRAL - (Q/Vc) * CENTRAL + (Q/Vp) * PERIPH;" if "2cmt" in model_type else "dxdt_CENTRAL = -CL/Vc * CENTRAL;"}
{"dxdt_PERIPH  = (Q/Vc) * CENTRAL - (Q/Vp) * PERIPH;" if "2cmt" in model_type else ""}
$TABLE double Cp = CENTRAL / Vc; capture Cp;
'

mod <- mread_cache("pkmodel", tempdir(), model_code)

# IIV via parameter variation (lognormal)
omega <- {iiv_omega}
idata <- data.frame(
  ID  = 1:N,
  CL  = {params.get("CL", 5)} * exp(rnorm(N, 0, sqrt(omega))),
  Vc  = {params.get("Vc", 50)} * exp(rnorm(N, 0, sqrt(omega))),
  {"KA  = " + str(params.get("KA", 1.0)) + " * exp(rnorm(N, 0, sqrt(omega)))," if "oral" in model_type else ""}
  {"Q   = " + str(params.get("Q", 2.0)) + " * exp(rnorm(N, 0, sqrt(omega)))," if "2cmt" in model_type else ""}
  {"Vp  = " + str(params.get("Vp", 80.0)) + " * exp(rnorm(N, 0, sqrt(omega)))," if "2cmt" in model_type else ""}
  stringsAsFactors = FALSE
)

# Dosing events
dose_event <- ev(
  amt  = {dosing.get("dose_mg", 100)},
  ii   = {dosing.get("interval_h", 24)},
  addl = {dosing.get("n_doses", 7) - 1},
  cmt  = {"1" if "oral" in model_type else "1"}
)

# Simulate
sim <- mod %>%
  idata_set(idata) %>%
  ev(dose_event) %>%
  mrgsim(end = {simulation_duration_h}, delta = 0.5) %>%
  as.data.frame()

# Summary statistics
sim_summary <- sim %>%
  group_by(time) %>%
  summarise(
    median = median(Cp),
    p5     = quantile(Cp, 0.05),
    p95    = quantile(Cp, 0.95),
    p10    = quantile(Cp, 0.10),
    p90    = quantile(Cp, 0.90),
    .groups = "drop"
  )

# Steady-state metrics (last dosing interval)
last_interval <- sim %>%
  filter(time > {simulation_duration_h - dosing.get("interval_h", 24)})
ss_auc   <- mean(tapply(last_interval$Cp, last_interval$ID,
                        function(x) sum(diff(unique(last_interval$time)) * x[-1])))
ss_cmax  <- median(tapply(last_interval$Cp, last_interval$ID, max))
ss_cmin  <- median(tapply(last_interval$Cp, last_interval$ID, min))

cat("\\nSS_METRICS_START\\n")
cat(sprintf("Steady-state Cmax (median): %.3f ng/mL\\n", ss_cmax))
cat(sprintf("Steady-state Cmin (median): %.3f ng/mL\\n", ss_cmin))
cat(sprintf("Steady-state AUCtau (mean): %.1f ng.h/mL\\n", ss_auc))
{_target_line}
cat("SS_METRICS_END\\n")

# Plot
p <- ggplot(sim_summary, aes(x = time)) +
  geom_ribbon(aes(ymin = p5, ymax = p95), fill = "#2166AC", alpha = 0.15) +
  geom_ribbon(aes(ymin = p10, ymax = p90), fill = "#2166AC", alpha = 0.25) +
  geom_line(aes(y = median), colour = "#2166AC", linewidth = 1.2) +
  {"geom_hline(yintercept = " + str(target_conc) + ", colour = 'red', linetype = 2, linewidth = 0.8) +" if target_conc else ""}
  labs(
    title    = "PK Simulation — {compound_name}",
    subtitle = "Median (line), 80% PI (dark band), 90% PI (light band)",
    x        = "Time (h)",
    y        = "Plasma Concentration (ng/mL)"
  ) +
  theme_bw(base_size = 13)
ggsave("{output_dir}/pk_simulation.png", p, width = 10, height = 6, dpi = 150)

write.csv(sim_summary, "{output_dir}/sim_summary.csv", row.names = FALSE)
cat("Simulation saved.\\n")
"""

    r_output = run_r_code(r_code)

    if "Error" in r_output and "SS_METRICS_START" not in r_output:
        log.append(f"\nR execution error:\n{r_output}")
        return "\n".join(log)

    log.append(f"\nDosing regimen: {dosing.get('dose_mg')} mg every {dosing.get('interval_h')} h × {dosing.get('n_doses')} doses")
    log.append(f"\n── Steady-State PK Metrics (N={n_subjects} virtual subjects) ──")
    in_block = False
    for line in r_output.splitlines():
        if "SS_METRICS_START" in line:
            in_block = True
            continue
        if "SS_METRICS_END" in line:
            in_block = False
            continue
        if in_block:
            log.append(f"  {line}")

    log.append(f"\nOutput saved to {output_dir}/:")
    log.append("  pk_simulation.png  — median + 80/90% PI band plot")
    log.append("  sim_summary.csv    — time-course summary statistics")

    return "\n".join(log)


# ─────────────────────────────────────────────────────────────────────────────
# Covariate Analysis
# ─────────────────────────────────────────────────────────────────────────────

def run_covariate_analysis(
    dataset_path: str,
    base_model_params: dict,
    covariates_to_test: list,
    pk_parameter_targets: list,
    method: str = "stepwise",
    output_dir: str = "./covariate_output",
) -> str:
    """Perform population PK covariate analysis using stepwise or SCM approach.

    Tests the impact of patient covariates (body weight, age, renal function,
    etc.) on PK parameters. Reports OFV change, parameter shift, and
    clinical relevance (>20% change in AUC criterion).

    Parameters
    ----------
    dataset_path : str
        Path to dataset CSV including covariate columns.
    base_model_params : dict
        Base model parameter estimates (from run_nlmixr2_model or NONMEM).
    covariates_to_test : list
        Covariate names as they appear in the dataset.
        Example: ['WT', 'AGE', 'CRCL', 'SEX', 'RACE']
    pk_parameter_targets : list
        PK parameters to test each covariate on.
        Example: ['CL', 'Vc']
    method : str
        'stepwise' (forward addition / backward elimination) or 'full_random'.
    output_dir : str
        Directory for covariate analysis output.
    """
    log = ["=" * 60]
    log.append("COVARIATE ANALYSIS")
    log.append("=" * 60)
    log.append(f"Dataset           : {dataset_path}")
    log.append(f"Covariates tested : {', '.join(covariates_to_test)}")
    log.append(f"PK targets        : {', '.join(pk_parameter_targets)}")
    log.append(f"Method            : {method}")

    os.makedirs(output_dir, exist_ok=True)

    r_code = f"""
suppressPackageStartupMessages({{
  library(nlmixr2)
  library(ggplot2)
  library(dplyr)
}})

pk_data  <- read.csv("{dataset_path}")
cov_list <- c({", ".join(f'"{c}"' for c in covariates_to_test)})
par_list <- c({", ".join(f'"{p}"' for p in pk_parameter_targets)})

cat("Covariate screening summary:\\n")
cat("Dataset: ", nrow(pk_data), "rows,", length(unique(pk_data$ID)), "subjects\\n\\n")

# Exploratory: ETAs vs covariates (requires fitted model object; using
# correlation as proxy for clinical relevance screening)
if (all(cov_list %in% names(pk_data))) {{
  id_data <- pk_data[!duplicated(pk_data$ID), c("ID", cov_list)]
  cat("COVARIATE_SUMMARY_START\\n")
  cat(sprintf("%-12s %-10s %-15s %-10s\\n", "Covariate", "N non-NA", "Range/Levels", "Type"))
  cat(paste(rep("-", 55), collapse=""), "\\n")
  for (cov in cov_list) {{
    vals <- id_data[[cov]]
    if (is.numeric(vals)) {{
      cat(sprintf("%-12s %-10d %-15s %-10s\\n",
        cov, sum(!is.na(vals)),
        paste0(round(min(vals, na.rm=T),1), "–", round(max(vals, na.rm=T),1)),
        "continuous"))
    }} else {{
      cat(sprintf("%-12s %-10d %-15s %-10s\\n",
        cov, sum(!is.na(vals)),
        paste0(levels(as.factor(vals)), collapse="/"),
        "categorical"))
    }}
  }}
  cat("COVARIATE_SUMMARY_END\\n")
}}

# Clinical relevance threshold guidance
cat("\\nCOV_GUIDANCE_START\\n")
cat("Covariate is clinically relevant if it causes > 20% change in AUC/Cmax.\\n")
cat("FDA guidance: dose adjustment warranted if exposure changes > 2-fold.\\n")
cat("Typical power model: PK_par = TVpar * (COV/COV_ref)^theta_cov\\n")
cat("  WT on CL: theta_cov ~ 0.75 (allometric scaling)\\n")
cat("  WT on Vc: theta_cov ~ 1.0\\n")
cat("  CRCL on CLr: theta_cov estimated from data (renal impairment)\\n")
cat("\\nForward inclusion: ΔOFV > 3.84 (χ², df=1, p<0.05)\\n")
cat("Backward elimination: ΔOFV > 6.63 (χ², df=1, p<0.01)\\n")
cat("COV_GUIDANCE_END\\n")

# ETA shrinkage warning
cat("\\nSHRINKAGE_NOTE\\n")
cat("If ETA shrinkage > 30%: individual estimates unreliable for covariate plots.\\n")
cat("Use population-level covariate analysis or NPDE-based diagnostics.\\n")
"""

    r_output = run_r_code(r_code)

    in_block = False
    for section in ["COVARIATE_SUMMARY", "COV_GUIDANCE", "SHRINKAGE_NOTE"]:
        for line in r_output.splitlines():
            if f"{section}_START" in line:
                in_block = True
                log.append(f"\n── {section.replace('_', ' ').title()} ──")
                continue
            if f"{section}_END" in line:
                in_block = False
                continue
            if in_block:
                log.append(f"  {line}")

    log.append("\n── Standard Covariate Testing Procedure ──")
    log.append("  Step 1 — Graphical inspection: ETA vs covariate scatterplots")
    log.append("  Step 2 — Forward addition: test each covariate (ΔOFV > 3.84)")
    log.append("  Step 3 — Build full forward model with all significant covariates")
    log.append("  Step 4 — Backward elimination: remove one-at-a-time (ΔOFV > 6.63)")
    log.append("  Step 5 — Evaluate final model: VPC, bootstrap, clinical relevance")

    return "\n".join(log)


# ─────────────────────────────────────────────────────────────────────────────
# Model Selection Guidance
# ─────────────────────────────────────────────────────────────────────────────

def compare_pk_models(
    model_results: list,
) -> str:
    """Compare population PK models and recommend the best based on standard criteria.

    Applies AIC, BIC, OFV likelihood ratio test, VPC pass/fail, and
    parsimony criteria. Outputs a ranked comparison table.

    Parameters
    ----------
    model_results : list
        List of dicts, each describing one model. Required keys:
        'name', 'ofv', 'n_params', 'n_obs', 'cov_successful', 'vpc_pass'.
        Optional: 'notes'.
        Example:
          [{'name': '1cmt_oral', 'ofv': 1200.5, 'n_params': 4,
            'n_obs': 800, 'cov_successful': True, 'vpc_pass': True},
           {'name': '2cmt_oral', 'ofv': 1185.2, 'n_params': 6,
            'n_obs': 800, 'cov_successful': True, 'vpc_pass': True}]
    """
    log = ["=" * 60]
    log.append("MODEL COMPARISON AND SELECTION")
    log.append("=" * 60)

    if not model_results:
        return "No model results provided."

    for m in model_results:
        m["aic"] = m["ofv"] + 2 * m["n_params"]
        m["bic"] = m["ofv"] + m["n_params"] * np.log(m["n_obs"])

    best_aic = min(model_results, key=lambda x: x["aic"])["aic"]

    log.append(f"\n{'Model':<20} {'OFV':>10} {'P':>5} {'AIC':>10} {'ΔAIC':>8} {'BIC':>10} {'Cov':>6} {'VPC':>6}")
    log.append("-" * 80)
    for m in sorted(model_results, key=lambda x: x["aic"]):
        d_aic = m["aic"] - best_aic
        cov_s = "✓" if m.get("cov_successful") else "✗"
        vpc_s = "✓" if m.get("vpc_pass") else "✗"
        log.append(
            f"  {m['name']:<18} {m['ofv']:>10.2f} {m['n_params']:>5} "
            f"{m['aic']:>10.2f} {d_aic:>8.2f} {m['bic']:>10.2f} {cov_s:>6} {vpc_s:>6}"
        )

    # LRT between consecutive models (sorted by n_params)
    sorted_models = sorted(model_results, key=lambda x: x["n_params"])
    log.append("\n── Likelihood Ratio Tests (LRT) ──")
    log.append("  χ² critical: df=1 → 3.84 (p<0.05), df=2 → 5.99, df=3 → 7.81")
    for i in range(len(sorted_models) - 1):
        base = sorted_models[i]
        full = sorted_models[i + 1]
        delta_ofv = base["ofv"] - full["ofv"]
        delta_p = full["n_params"] - base["n_params"]
        from scipy.stats import chi2
        p_val = 1 - chi2.cdf(delta_ofv, df=delta_p) if delta_ofv > 0 else 1.0
        sig = "✓ significant" if p_val < 0.05 else "not significant"
        log.append(
            f"  {base['name']} → {full['name']}: "
            f"ΔOFV={delta_ofv:.2f}, Δp={delta_p}, p={p_val:.4f}  [{sig}]"
        )

    # Recommendation
    log.append("\n── Recommendation ──")
    candidates = [m for m in model_results if m.get("cov_successful") and m.get("vpc_pass")]
    if candidates:
        best = min(candidates, key=lambda x: x["bic"])
        log.append(f"  Recommended model: {best['name']}")
        log.append("  Rationale: lowest BIC among models with successful covariance step and VPC pass.")
    else:
        log.append("  No model passed all criteria. Review covariance step failures and VPC.")

    log.append("\n── Selection Hierarchy ──")
    log.append("  1. Covariance step must succeed (model stability)")
    log.append("  2. VPC must be acceptable (predictive performance)")
    log.append("  3. ΔOFV ≥ 3.84 (LRT, p<0.05) to justify additional parameter")
    log.append("  4. Lowest BIC among qualifying models (parsimony)")
    log.append("  5. Clinical plausibility of parameter estimates")

    return "\n".join(log)
